name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Klona koden
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET för backend
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    # Bygg backend
    - name: Build Backend
      working-directory: ./ogabogaShop
      run: |
        dotnet restore
        dotnet build --configuration Release

    # Kör enhetstester
    - name: Run Tests
      working-directory: ./Webshop.Tests
      run: dotnet test --no-build --verbosity normal

    # Setup Node.js för frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Bygg och testa frontend (om package.json finns)
    - name: Build and Test Frontend
      if: exists('./frontend/package.json')
      working-directory: ./frontend
      run: |
        npm install
        npm run build
        npm run test
