name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Klona koden
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    # Bygg och testa backend
    - name: Build and Test Backend
      working-directory: ./backend
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet test --no-build --verbosity normal

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Bygg och testa frontend
    - name: Build and Test Frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build
        npm run test
